# -*- coding: utf-8 -*-
"""Openbb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VyEAUNf1mzWfa0rScrqr7w0tg22cDXrR
"""

!pip install openbb

from openbb_terminal.sdk import openbb

df_daily = openbb.stocks.load(symbol = 'ndaq')

df_daily.head()

df_daily.tail()